<?php
/**
 * Integration check for the optimizer core, run inside the container against a
 * real WordPress:  wp eval-file wp-content/plugins/patu/tests/core-check.php
 * with -e PATU_KEY="$PATU_KEY".  Prints PASS/FAIL lines; exits non-zero on any
 * failure so CI/ad-hoc runs can gate on it.
 *
 * @package Patu
 */

$fails = 0;
function check( $label, $cond ) {
	global $fails;
	echo ( $cond ? 'PASS' : 'FAIL' ) . '  ' . $label . "\n";
	if ( ! $cond ) {
		$fails++;
	}
}

update_option( 'patu_api_key', getenv( 'PATU_KEY' ) );
update_option( 'patu_auto', '0' );   // test the manual path first.
update_option( 'patu_backup', '1' );

require_once ABSPATH . 'wp-admin/includes/image.php';
require_once ABSPATH . 'wp-admin/includes/media.php';

/** Create an attachment from generated bytes; returns [id, file]. */
function make_attachment( $bytes, $name, $mime ) {
	$up = wp_upload_bits( $name, null, $bytes );
	if ( ! empty( $up['error'] ) ) {
		echo 'upload error: ' . $up['error'] . "\n";
		exit( 1 );
	}
	$id   = wp_insert_attachment(
		array(
			'post_mime_type' => $mime,
			'post_title'     => $name,
			'post_status'    => 'inherit',
		),
		$up['file']
	);
	$meta = wp_generate_attachment_metadata( $id, $up['file'] );
	wp_update_attachment_metadata( $id, $meta );
	return array( $id, $up['file'] );
}

function make_jpeg( $w, $h, $q = 95 ) {
	$im = imagecreatetruecolor( $w, $h );
	for ( $y = 0; $y < $h; $y++ ) {
		for ( $x = 0; $x < $w; $x++ ) {
			imagesetpixel( $im, $x, $y, imagecolorallocate( $im, (int) ( $x * 255 / $w ), (int) ( $y * 255 / $h ), ( $x + $y ) % 256 ) );
		}
	}
	ob_start();
	imagejpeg( $im, null, $q );
	return ob_get_clean();
}

function make_png( $w, $h ) {
	$im = imagecreatetruecolor( $w, $h );
	for ( $y = 0; $y < $h; $y++ ) {
		for ( $x = 0; $x < $w; $x++ ) {
			imagesetpixel( $im, $x, $y, imagecolorallocate( $im, (int) ( $x * 255 / $w ), 0, (int) ( $y * 255 / $h ) ) );
		}
	}
	ob_start();
	imagepng( $im );
	return ob_get_clean();
}

echo "== JPEG optimize ==\n";
list( $id, $file ) = make_attachment( make_jpeg( 1200, 900 ), 'patu-core.jpg', 'image/jpeg' );
$files             = Patu_Optimizer::files_for_attachment( $id );
check( 'attachment has original + sizes (>=2 files)', count( $files ) >= 2 );

$before = array();
foreach ( $files as $f ) {
	$before[ $f ] = filesize( $f );
}
$meta_before = wp_get_attachment_metadata( $id );

$r = Patu_Optimizer::optimize_attachment( $id );
echo "  result: optimized={$r['optimized']} failed={$r['failed']} saved={$r['saved']}\n";
check( 'at least one file optimized', $r['optimized'] >= 1 );
check( 'no failures', 0 === $r['failed'] );
check( 'reported saved > 0', $r['saved'] > 0 );

$all_smaller_or_equal = true;
$any_smaller          = false;
$all_valid            = true;
foreach ( $files as $f ) {
	clearstatcache( true, $f );
	$now = filesize( $f );
	if ( $now > $before[ $f ] ) {
		$all_smaller_or_equal = false;
	}
	if ( $now < $before[ $f ] ) {
		$any_smaller = true;
	}
	$info = @getimagesize( $f );
	if ( false === $info || 'image/jpeg' !== $info['mime'] ) {
		$all_valid = false;
	}
}
check( 'never bigger (no file grew)', $all_smaller_or_equal );
check( 'at least one file shrank', $any_smaller );
check( 'all files still valid JPEGs', $all_valid );

$meta_after = wp_get_attachment_metadata( $id );
check( 'attachment metadata unchanged (dimensions/sizes)', wp_json_encode( $meta_before ) === wp_json_encode( $meta_after ) );
check( 'optimization recorded on attachment', Patu_Optimizer::is_optimized( $id ) );

$uploads = wp_get_upload_dir();
check( 'backups directory created', is_dir( $uploads['basedir'] . '/patu-originals' ) );

echo "== idempotent / never-bigger on re-run ==\n";
$r2 = Patu_Optimizer::optimize_attachment( $id );
check( 're-run optimizes nothing new (already processed)', 0 === $r2['optimized'] );

echo "== restore ==\n";
$rest = Patu_Optimizer::restore_attachment( $id );
echo "  restored {$rest['restored']} files\n";
$restored_ok = true;
foreach ( $files as $f ) {
	clearstatcache( true, $f );
	if ( filesize( $f ) !== $before[ $f ] ) {
		$restored_ok = false;
	}
}
check( 'restore returns every file to its exact original size', $restored_ok );
check( 'optimization meta cleared after restore', ! Patu_Optimizer::is_optimized( $id ) );

echo "== PNG left untouched (v1) ==\n";
list( $pid, $pfile ) = make_attachment( make_png( 400, 300 ), 'patu-core.png', 'image/png' );
$psize               = filesize( $pfile );
$pr                  = Patu_Optimizer::optimize_attachment( $pid );
clearstatcache( true, $pfile );
check( 'PNG reported as skipped/unsupported', isset( $pr['skipped'] ) && 'unsupported' === $pr['skipped'] );
check( 'PNG file untouched', filesize( $pfile ) === $psize );

echo "== never-broken: bad endpoint does not fatal ==\n";
add_filter( 'patu_endpoint', function () { return 'https://patu.dev/does-not-exist-xyz'; } );
list( $bid, $bfile ) = make_attachment( make_jpeg( 300, 200 ), 'patu-bad.jpg', 'image/jpeg' );
$bsize               = filesize( $bfile );
$br                  = Patu_Optimizer::optimize_attachment( $bid );
clearstatcache( true, $bfile );
check( 'failed API call recorded as failure, not fatal', $br['failed'] >= 1 && 0 === $br['optimized'] );
check( 'original kept intact after a failed optimize', filesize( $bfile ) === $bsize );

// cleanup
wp_delete_attachment( $id, true );
wp_delete_attachment( $pid, true );
wp_delete_attachment( $bid, true );

echo "\n" . ( 0 === $fails ? 'ALL PASSED' : $fails . ' FAILED' ) . "\n";
exit( 0 === $fails ? 0 : 1 );
